src/create/schema/object.test.ts, src/create/schema/object.ts
At the moment Zod Strict Objects render `additionalProperties: true` when they should be rendering `additionalProperties: false`
=> Fix Zod strict objects `additionalProperties` mapping

README.md, src/create/schema/index.test.ts, src/create/schema/index.ts, src/create/schema/preprocess.test.ts, src/create/schema/preprocess.ts, src/create/schema/transform.test.ts, src/create/schema/transform.ts, src/extendZod.ts
This allows users to override the creation type of a ZodEffect. Sometimes users may not change the type very much.
```ts
z.string().transform((arg) => arg.toLowerCase())
```
In this case the type remains a string. However, our library does not know that.
A user can either wrap it in a ZodPipeline and parse it again or they can tell our library to trust that the type has not changed.
```ts
z.string()
.transform((arg) => arg.toLowerCase())
.pipe(z.string())
```
or you can set the 
```ts
z.string()
.transform((arg) => arg.toLowerCase())
.openapi({effectType: 'input'})
```
or you can say "trust me"
```ts
z.string()
.transform((arg) => arg.toLowerCase())
.openapi({type: 'string'})
```
=> Add override to `ZodEffects` types and default `preprocess` to output type

package.json, yarn.lock
This will allow consumers to re-lock to fix issues going forward
=> Unpin `openapi3-ts` and `yaml` versions

README.md, src/create/components.test.ts, src/create/components.ts, src/create/document.test.ts, src/create/document.ts, src/create/responses.test.ts, src/create/responses.ts
Uses the `headers` response key instead of `responseHeaders`. This was a mistake on my behalf.
I haven't advertised this library anywhere big yet intentionally so I'm going to go with minor change for now.
=> Use `headers` key for response headers

src/create/schema/nullable.test.ts, src/create/schema/nullable.ts
https://github.com/OAI/OpenAPI-Specification/blob/main/proposals/2019-10-31-Clarify-Nullable.md#if-a-schema-specifies-nullable-true-and-enum-1-2-3-does-that-schema-allow-null-values-see-1900
=> Fix nullable enums in 3.0.0

src/create/schema/object.test.ts, src/create/schema/object.ts, src/extendZod.test.ts, src/extendZod.ts
Partially resolves https://github.com/samchungy/zod-openapi/issues/57
Fixes the extend logic to not create an allOf when an .extend overrides a field. It is too hard to calculate if the new type (String checks, number checks etc) is derivative of an existing type. Additionally, Zod does not care about the base field meaning even if we were to add an `allOf` it would not match the Zod behaviour.
https://json-schema.org/understanding-json-schema/reference/combining.html#allof
=> Do not create allOf schema when extend overrides a field

README.md, src/create/schema/object.test.ts, src/create/schema/object.ts
Adds `catchAll` additionalProperties mapping for ZodObjects
=> Add ZodObject .catchall() support

README.md, src/create/components.test.ts, src/create/components.ts, src/create/document.ts, src/create/parameters.test.ts, src/create/parameters.ts
Technically another breaking change - but no one has complained yet so I will assume nobody is using this right now.
Having `requestParams` on the components doesn't make sense as it confuses and right now uses the name as the ref.
This adds another way to register parameters.
=> Fix manual parameter components

src/create/document.test.ts, src/create/schema/metadata.test.ts, src/create/schema/metadata.ts, src/create/schema/nullable.test.ts, src/create/schema/object.test.ts, src/create/schema/object.ts
At the moment if you make an extended schema strict, it will generate an incorrect schema.
https://json-schema.org/understanding-json-schema/reference/object.html#id6
This changes the behaviour from:
```ts
{
allOf: [
schema1,
{ additionalProperties: false }
]
}
```
to 
```ts
{
allOf: [
schema1,
],
additionalProperties: false
}
```
=> Enhance extend allOf behaviour

scripts/copyTypes.ts, src/index.ts, src/openapi3-ts/dist/index.ts, src/openapi3-ts/dist/oas30.ts, src/openapi3-ts/dist/oas31.ts
https://github.com/samchungy/zod-openapi/pull/94 technically introduced a breaking change to anyone with Typescript < 5. This should hopefully be a happy inbetween.
Resolves https://github.com/samchungy/zod-openapi/issues/105
=> Fix type exports

src/extendZod.ts
I'm using a monorepo with TS project references and our own declaration merging on zod types, and sometimes I get weird errors, at least with `tsc -b`...replacing `ZodSchema` (which is an export alias) with `ZodType` (the "real" name) makes the error go away.
=> fix: use ZodType in declaration merging instead of ZodSchema

README.md, src/api.ts, src/index.ts
To make the usage clearer, hide all of these extra methods under the `api` alias
=> Export additional elements as api

src/create/components.ts, src/create/content.ts, src/create/parameters.ts, src/create/responses.ts, src/create/schema/parsers/discriminatedUnion.ts, src/create/schema/parsers/index.ts, src/create/schema/parsers/manual.ts, src/create/schema/parsers/object.ts, src/create/schema/parsers/optional.ts, src/zodType.ts
Had a consumer message me about issues. Turns out there is a variance in versions of Zod between the Zod version his library was using versus the Zod version the library was relying on. This meant that `instanceof` check was not working as intended. Instead, we will now rely on zodType._def.typeName. I am avoiding pulling in the enum to avoid version drift
https://github.com/colinhacks/zod/pull/2459 prevents us from having nice types
=> Avoid instanceof checks and rely on typeName

src/create/schema/index.test.ts, src/create/schema/parsers/optional.ts
`ZodDefault` should be considered optional only in `input` states
Encountered this bug in my project
```js
responses: {
200: {
description: "The Job that was created",
content: {
"application/json": {
schema: z.object({
data: JobSchema,
}),
},
},
},
}
// ...
const JobSchema = z.object({
jobId: z.string().default(() => uuid()),
userId: z.string(),
schedule: z.string(),
enabled: z.boolean(),
endpoint: EndpointSchema,
});
```
Resulting in OpenAPI spec that didn't list `jobId` as required:
```
"schema": {
"type": "object",
"properties": {
"data": {
"type": "object",
"properties": {
"jobId": {
"type": "string",
"default": "97e6c4a9-f00c-427f-b1fa-87f115621ba8"
},
// ....
},
"required": ["userId", "schedule", "enabled", "endpoint"]
}
},
"required": ["data"]
}
```
=> fix: default should be nonoptional in output state

README.md
I'm unsure where does the `:param` syntax comes from since I couldn't find it in the OpenAPI 3.x spec.
Some OpenAPI generators (like Orval) fail to extract the path parameters if they are not written in the form of `{param}`.
=> README: Fix path parameters extraction

src/create/parameters.test.ts, src/create/parameters.ts
=> Duplicate description on schemas used in parameters

esbuild.esm.mjs, package.json
Currently, Node.js always used the CommonJS version even when imported from an ES module. That's because ES modules require an `exports` key to be defined in `package.json`.
(The `module` key is only used by bundlers, AFAIK.)
Also, since there is no `type: "module"` configured, all ES modules need to have the `.mjs` extension (otherwise they will go through the CommonJS compatibility shim which again, will cause the import to fail). Fix that as well.
=> Fix ESM importing on Node.js

src/create/parameters.ts
This did not seem to work if the the same parameter component ref was being used in multiple path's `params: [paramRef]` arrays. I believe this is because `type` variable (passed as a parameter) was `undefined` in that case (being called from `createManualParameters`, it would instead come from `zodSchema._def.openapi.type`).
Being `undefined`, the `if` check would always fail if such a parameter already existed (even if it was identical).
This fixes it - it always compares with the value the parameter object would potentially be created with later on, ie. `paramType` and `paramName`.
_Observation:_
`const paramType = zodSchema._def?.openapi?.param?.in ?? component?.in ?? type` prefers the component's type instead of the passed `type` parameter.
Even in case the `type` mismatches (eg. …
=> Fix duplicate parameter component check

package.json, pnpm-lock.yaml, src/create/document.test.ts, src/create/schema/index.test.ts, src/create/schema/parsers/discriminatedUnion.test.ts, src/create/schema/parsers/index.ts, src/create/schema/parsers/literal.test.ts, src/create/schema/parsers/literal.ts, src/create/schema/parsers/null.test.ts, src/create/schema/parsers/null.ts, src/create/schema/parsers/optional.test.ts, src/create/schema/parsers/optional.ts, src/openapi3-ts/dist/model/openapi31.ts
ZodLiteral values will now be represented using the [const](https://json-schema.org/understanding-json-schema/reference/const#constant-values) keyword instead of a single value enum.
The following object, this will be now rendered as follows in OpenAPI 3.1
```ts
z.object({
foo: z.literal('foo')
});
```
```diff
foo:
type: 'string'
-  enum:
-    - 'foo'
+  const: 'foo'
```
=> Support OpenAPI 3.1 `const` value

README.md, src/create/schema/parsers/discriminatedUnion.test.ts, src/create/schema/parsers/discriminatedUnion.ts
=> Support new discriminator key options

.eslintignore, .gitignore, crackle.config.ts, package.json, src/api.ts, src/entries/api.ts, src/index.ts, tsconfig.json
The `api` export was only ever intended for plugin/integration access however in Intellisense it appears as one of the first options. This moves it to a subpath import so the main functionality is clearer upon import. This moves it to under `zod-openapi/api`
=> Move api import to subpath

README.md, src/create/callbacks.ts, src/create/components.ts, src/create/content.ts, src/create/document.test.ts, src/create/document.ts, src/create/parameters.ts, src/create/paths.ts, src/create/responses.ts, src/create/schema/index.ts, src/create/schema/parsers/date.test.ts, src/create/schema/parsers/date.ts, src/create/schema/parsers/index.ts, src/testing/state.ts
closed https://github.com/samchungy/zod-openapi/issues/305
Hi samchungy.
I have added a feature that resolves #305.
Added an options object argument to createDocument function to allow setting the value of  `defaultDateSchema`.
After the SchemaState object is created, it is passed to each function by passing an options object to SchemaState object.
If you see any problems or shortcomings, please point them out to me.
=> Add default date schema option

src/create/components.ts, src/create/parameters.ts
This one slipped through unintentionally as a breaking change:
https://github.com/samchungy/zod-openapi/pull/330/files#diff-ddd2a05e83d80d4b6e2db78d84993a94c09f9c56b563abbb6e3de61b422f7f38R132
https://github.com/samchungy/fastify-zod-openapi/issues/166
https://github.com/samchungy/fastify-zod-openapi/pull/165
TODO: Some unit tests should have broken... Clearly missing something here and definitely due for a re-write especially with 3 optionals...
=> Fix createParamOrRef

src/create/components.ts, src/create/document.test.ts, src/create/parameters.test.ts, src/create/parameters.ts, src/create/responses.ts, src/create/schema/index.ts, src/create/schema/metadata.test.ts, src/create/schema/metadata.ts, src/create/schema/parsers/catch.test.ts, src/create/schema/parsers/catch.ts, src/create/schema/parsers/default.test.ts, src/create/schema/parsers/default.ts, src/create/schema/parsers/index.ts, src/create/schema/parsers/lazy.test.ts, src/create/schema/parsers/manual.ts, src/create/schema/parsers/nullable.test.ts, src/create/schema/parsers/object.test.ts, src/create/schema/parsers/object.ts, src/create/schema/parsers/pipeline.ts, src/create/schema/parsers/transform.ts, src/create/schema/parsers/union.ts, src/create/schema/single.test.ts, src/extendZod.test.ts, src/extendZod.ts, src/extendZodTypes.ts, src/openapi.ts
Resolves https://github.com/samchungy/zod-openapi/issues/303
`.openapi()` behaves a little differently now.
It now will attempt to store any `previous` openapi state and use it.
1. Unintuitive Extension
```ts
const FooSchema = z.string().openapi({ ref: 'string' });
const BarSchema = z.object({
a: FooSchema,
b: FooSchema.openapi({ description: 'foo' }),
});
createSchema(BarSchema)
```
This currently generates the following:
```ts
{
schema: {
type: 'object',
properties: {
a: { '$ref': '#/components/schemas/string' },
b: { type: 'string', description: 'foo' }
},
required: [ 'a', 'b' ]
},
components: { string: { type: 'string' } }
}
```
However, it's clear that the user simply wanted to reuse the FooSchema but describe it as something else later on.
After:
```ts
{
schema: {
type: 'object', …
```
=> `.openapi()` Breaking Change

README.md, src/create/schema/index.test.ts, src/create/schema/parsers/bigint.test.ts, src/create/schema/parsers/bigint.ts, src/create/schema/parsers/index.ts
I have implemented support for bigint type 😄
The schema is output as integer(int64).
If I am missing any considerations, please point them out🙇🏻‍♂️
=> Add support for bigint

package.json, src/create/schema/index.ts, src/create/schema/metadata.test.ts, src/entries/extend.ts, src/extendZod.test.ts, src/extendZod.ts, src/extendZodTypes.ts, tsconfig.json
Avoid serializing them and encountering issues circular references
Resolves #392
=> Replace current and previous properties with symbols to allow JSON serialization of zod schema

src/create/schema/index.ts, src/entries/extend.ts, src/extendZod.test.ts, src/extendZod.ts, src/extendZodSymbols.ts, src/extendZodTypes.ts
=> Fix Manual Type Extensions

src/create/schema/parsers/object.test.ts, src/create/schema/parsers/object.ts, src/create/schema/parsers/transform.ts
Sets `additionalProperties: true` to explicitly `true` when `.passthrough()` is added to a ZodObject.
https://github.com/fastify/fast-json-stringify#additional-properties
https://github.com/samchungy/fastify-zod-openapi/issues/224
=> Explicitly set additionalProperties for `.passthrough()`

.changeset/easy-crews-call.md, src/create/schema/override.ts, src/create/schema/schema.ts, src/create/schema/tests/mini.test.ts, src/create/schema/tests/unionMini.test.ts
The correct way to read a schema's spec appears to be through `z.globalRegistry` instead of `.meta()`, which doesn't work for `zod/mini` types. I think the type assertion that was required with `meta()` points to the same conclusion.
Fixes #519
=> Fix `zod/mini` compatibility

src/create/schema/schema.ts
The defaults were both in the default parameter value and later set using `??=`.
Note that the default for `registry` is a bit different for the following `??=` (hopefully better).
=> refactor: Redundant argument defaults in `createSchema`
