- src/create/schema/number.test.ts
- src/create/schema/number.ts
Fixes the mapping of exclusive minimum and mapping
> Fix exclusive minimum and maximum number mapping

- README.md
- src/create/schema/catch.test.ts
- src/create/schema/catch.ts
- src/create/schema/index.test.ts
- src/create/schema/index.ts
> Add ZodCatch support

- src/create/schema/unknown.ts
Add advice to add ZodPipeline to error message
> Optimise ZodEffects error message

- src/create/components.ts
- src/create/document.ts
Preserves existing manually declared components
> Preserves existing manually declared components

- README.md
- src/create/components.test.ts
- src/create/components.ts
- src/create/schema/index.ts
> Allow registering manual schema in any order

- README.md
- src/create/components.test.ts
- src/create/components.ts
- src/create/document.ts
- src/create/parameters.ts
- src/create/schema/index.ts
> Allow manual parameters component registration

- README.md
- src/create/components.ts
- src/create/document.test.ts
- src/create/schema/index.test.ts
- src/create/schema/index.ts
- src/create/schema/lazy.test.ts
- src/create/schema/lazy.ts
> Add Zod Lazy support

- README.md
- src/create/schema/brand.test.ts
- src/create/schema/brand.ts
- src/create/schema/index.test.ts
- src/create/schema/index.ts
> Add ZodBranded support

- README.md
- src/create/components.test.ts
- src/create/components.ts
- src/create/document.ts
Technically a breaking change but it wasn't working before?
> Fix manual header component registration

- README.md
- src/create/components.test.ts
- src/create/components.ts
- src/create/document.ts
Changes the logic to render manually registered components last
Resolves https://github.com/samchungy/zod-openapi/issues/68
> Render Manual Components Last

- README.md
- src/create/schema/pipeline.test.ts
- src/create/schema/pipeline.ts
- src/create/schema/transform.ts
- src/testing/state.ts
> Add ZodPipeline validation check

- src/index.ts
Resolves https://github.com/samchungy/zod-openapi/issues/91
> Export openapi3-ts folder as types

- src/create/parameters.ts
- src/create/responses.ts
- src/create/schema/object.ts
- src/create/schema/optional.test.ts
- src/create/schema/optional.ts
Resolves https://github.com/samchungy/zod-openapi/issues/93
> Avoid `isOptional()`

- src/create/components.ts
- src/create/document.test.ts
- src/create/schema/index.test.ts
- src/create/schema/index.ts
- src/create/schema/lazy.test.ts
- src/create/schema/lazy.ts
Resolves https://github.com/samchungy/zod-openapi/issues/99, https://github.com/samchungy/zod-openapi/pull/92
> Enhance ZodLazy support

- .github/workflows/release.yml
At the moment it's hard to know what PRs a release contains. Hopefully this should link the release notes to the issue
> Optimise the release experience

- src/create/components.ts
- src/create/content.ts
- src/create/parameters.ts
- src/create/responses.ts
- src/create/schema/array.ts
- src/create/schema/brand.ts
- src/create/schema/catch.ts
- src/create/schema/default.ts
- src/create/schema/discriminatedUnion.ts
- src/create/schema/index.test.ts
- src/create/schema/index.ts
- src/create/schema/intersection.ts
- src/create/schema/lazy.test.ts
- src/create/schema/lazy.ts
- src/create/schema/nullable.ts
- src/create/schema/object.ts
- src/create/schema/optional.ts
- src/create/schema/pipeline.ts
- src/create/schema/preprocess.ts
- src/create/schema/record.ts
- src/create/schema/refine.ts
- src/create/schema/set.ts
- src/create/schema/transform.ts
- src/create/schema/tuple.ts
- src/create/schema/union.ts
- src/testing/state.ts
fixes the issue I mentioned on comments to #102
> Optimise ZodLazy recursive error messaging

- src/create/schema/object.ts
Just aligning with consistency for the rest of the repo.
> Omit undefined `required` value

- src/create/document.test.ts
- src/create/schema/index.ts
- src/create/schema/lazy.test.ts
@samchungy the changes you made to my PR re-broke an issue I had come across...but I didn't mention it or think to add tests for it.
So, I added some more thorough failing tests and fixed the issue
> re-fix circular schema and cycle detection issues

- src/create/components.ts
- src/create/content.ts
- src/index.ts
> Export functions for fastify-zod-openapi

- README.md
- package.json
- src/create/schema/index.test.ts
- src/create/schema/parsers/index.ts
- src/create/schema/parsers/readonly.test.ts
- src/create/schema/parsers/readonly.ts
- src/zodType.ts
- yarn.lock
Support ZodReadonly: https://github.com/colinhacks/zod/pull/2634
> Support ZodReadonly

- esbuild.esm.mjs
- esbuild.mjs
- package.json
Should result in a slightly smaller package as well as less file reads when loading in the package
> Bundle Package with esbuild

- README.md
- docs/comparisons.md
- src/create/schema/index.ts
- src/create/schema/parsers/union.test.ts
- src/create/schema/parsers/union.ts
- src/extendZod.ts
Resolves https://github.com/samchungy/zod-openapi/issues/183
> Add unionOneOf

- src/create/document.test.ts
- src/create/schema/metadata.ts
- src/create/schema/parsers/nullable.test.ts
- src/create/schema/parsers/nullable.ts
- src/openapi.ts
Resolves https://github.com/samchungy/zod-openapi/issues/186
> Fix Nullable Behaviour

- README.md
- src/create/schema/parsers/object.test.ts
- src/create/schema/parsers/object.ts
- src/create/schema/parsers/optional.ts
> Ignore ZodNever and ZodUndefined

- src/create/schema/parsers/manual.ts
- src/create/schema/parsers/transform.test.ts
- src/create/schema/parsers/transform.ts
> Update ZodTransform `effectType` error messages

- src/create/schema/index.test.ts
- src/create/schema/index.ts
- src/create/schema/metadata.test.ts
> Remove duplicate descriptions on referenced schemas

- src/create/schema/parsers/optional.test.ts
- src/create/schema/parsers/optional.ts
Add missing effect type handling
> Add default effect type handling

- README.md
- src/create/schema/parsers/index.ts
- src/create/schema/parsers/string.test.ts
- src/create/schema/parsers/string.ts
> Support `.base64()` string `contentEncoding`

- src/create/callbacks.ts
- src/create/components.test.ts
- src/create/components.ts
- src/create/document.test.ts
- src/create/document.ts
- src/create/paths.ts
> Add support for callbacks

- src/create/schema/parsers/intersection.test.ts
- src/create/schema/parsers/intersection.ts
https://github.com/rhinobase/hono-openapi/issues/3#issuecomment-2466572269
> Update Intersection Parser

- README.md
- src/create/document.ts
- src/create/schema/parsers/discriminatedUnion.test.ts
- src/create/schema/parsers/discriminatedUnion.ts
https://github.com/samchungy/zod-openapi/discussions/364
> Add enforceDiscriminatedUnionComponents

- src/entries/api.ts
https://github.com/samchungy/fastify-zod-openapi/issues/210
> Export getZodObject via zod-openapi/api

- src/create/schema/parsers/nullable.test.ts
- src/create/schema/parsers/nullable.ts
Resolves https://github.com/samchungy/zod-openapi/issues/425
> Fix nullable const/enum behaviour

- package.json
- pnpm-lock.yaml
- src/create/schema/parsers/object.test.ts
- src/create/schema/parsers/optional.ts
Resolves https://github.com/samchungy/zod-openapi/issues/431
> Handle optional undefined

- src/create/paths.ts
Fixes https://github.com/samchungy/zod-openapi/issues/437
> Remove ref from request body

- src/openapi.ts
Resolves https://github.com/samchungy/zod-openapi/issues/436
> Support 3.1.1

- package.json
_Increase beer by beer%_ 🚀  add a button on npm which brings you to a popup in github:
Alternatively you can use https://github.com/sponsors/samchungy directly
> Add a beer button to npm

- .changeset/moody-books-cover.md
- src/create/schema/override.ts
- src/create/schema/tests/object.test.ts
- src/create/schema/tests/undefined.test.ts
Resolves https://github.com/samchungy/zod-openapi/issues/479
> Change ZodUndefined behaviour

- src/create/components.test.ts
- src/create/components.ts
- src/create/document.test.ts
Resolves https://github.com/samchungy/zod-openapi/issues/493
> Fix manual component registration
